{
  imports = [
    ./core/audio.nix
    ./core/bluetooth.nix
    ./core/boot.nix
    ./programs/env.nix
    ./core/fonts.nix
    ./services/geoclue.nix
    ./core/maintenance.nix
    ./core/networking.nix
    ./core/printing.nix
    ./programs/neovim.nix
    ./programs/portals.nix
    ./core/settings.nix
    ./core/shell.nix
    ./programs/thunar.nix
    ./core/time.nix
    ./core/users.nix
    ./programs/ui.nix
    ./programs/sddm.nix
    ./programs/gaming.nix
  ];
}
