# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.kernelModules = [];
    extraModulePackages = [];
    kernelModules = ["kvm-intel"];
    initrd.availableKernelModules = ["xhci_pci" "ahci" "sd_mod" "rtsx_pci_sdmmc"];
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-91522ec1-78c1-415d-8140-faf2d546e209";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-91522ec1-78c1-415d-8140-faf2d546e209".device = "/dev/disk/by-uuid/91522ec1-78c1-415d-8140-faf2d546e209";

  fileSystems."/boot" = {
    device = "systemd-1";
    fsType = "autofs";
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
